### PR TITLE
Rapha.btc bounty submission

### PR DESCRIPTION
**Pull request by Rapha-btc**
please check if this is useful. Ty Publius and WAB. Cool exercise!

### CODE REVIEW

**Comment by whoabuddy** [comment]
Thanks for this, great turnaround time!

Few quick questions:

- what does the default env file look like with this config? The default contained minimal info and this seems to add a few extra parameters. Are users expected to manage them or are they optional?
- why modify the existing script for the faucet drip vs creating a new one? We don't want to knock out the old code it should remain and new files used for new tools.
- will need to know if agents can use this or not, main tooling before defaulted to testnet and this uses mainnet, to be clear I think using mainnet is a good thing but other parts might need to be transitioned to support it.

I'll do a review against the criteria outlined in the bounty tomorrow and see if I have any other items to address.

Were you planning to submit a PR for the `ai-agent-crew` repo using these new tools as well?

**Comment by whoabuddy** [comment]
Ok looking at each script in more detail, I think there's a small disconnect in how these work. Each script should run on it's own with Bun, which means an agent can use it as a tool

For example:
```
bun run src/wallet/get-wallet-status.ts
```
returns
```
Account index: 0
Account address: ST2HQ5J6RP8HSQE9KKGWCHW9PT9SVE4TDGBZQ3EKR
Nonce: 0
```

The output of the script is the information passed to the agent when they use the tool.

Another example that requires an argument:
```
bun run src/wallet/get-transaction-status.ts
```

If you run it without the TXID it returns an error that informs the LLM of the mistake and how to correct it:
```
No transaction ID provided, exiting...
```

Or it will provide a result if called correctly:
```
bun run src/wallet/get-transaction-status.ts 0xf6303f3bc492b8fbc2153548ef7fe747d964683fe41278da63dfc7c1d3b6308e
```
returns:
```
success
```

This can be as simple or as complicated as the tool requires, e.g. the full tx info is available too:
`bun run src/wallet/get-transaction.ts 0xf6303f3bc492b8fbc2153548ef7fe747d964683fe41278da63dfc7c1d3b6308e` returns:
```
{
  tx_id: "0xf6303f3bc492b8fbc2153548ef7fe747d964683fe41278da63dfc7c1d3b6308e",
  nonce: 3716,
  fee_rate: "180",
  sender_address: "ST2QKZ4FKHAH1NQKYKYAYZPY440FEPK7GZ1R5HBP2",
  sponsored: false,
  post_condition_mode: "deny",
  post_conditions: [],
  anchor_mode: "any",
  is_unanchored: false,
  block_hash: "0x424ebbb5904021d863f67f61fe34987093ac289d6c78f41bbac63d3dc7476b5d",
  parent_block_hash: "0xf616660fc9f6eb8fed856d29516a4f2798164973f7cbf5e1271776703e8c5d95",
  block_height: 5796,
  block_time: 1718388205,
  block_time_iso: "2024-06-14T18:03:25.000Z",
  burn_block_height: 14272,
  burn_block_time: 1718388195,
  burn_block_time_iso: "2024-06-14T18:03:15.000Z",
  parent_burn_block_time: 1718387978,
  parent_burn_block_time_iso: "2024-06-14T17:59:38.000Z",
  canonical: true,
  tx_index: 1,
  tx_status: "success",
  tx_result: {
    hex: "0x0703",
    repr: "(ok true)",
  },
  microblock_hash: "0x",
  microblock_sequence: 2147483647,
  microblock_canonical: true,
  event_count: 1,
  events: [
    {
      event_index: 0,
      event_type: "stx_asset",
      tx_id: "0xf6303f3bc492b8fbc2153548ef7fe747d964683fe41278da63dfc7c1d3b6308e",
      asset: [Object ...],
    }
  ],
  execution_cost_read_count: 0,
  execution_cost_read_length: 0,
  execution_cost_runtime: 0,
  execution_cost_write_count: 0,
  execution_cost_write_length: 0,
  tx_type: "token_transfer",
  token_transfer: {
    recipient_address: "ST38RMDQFVC462DSJ1CPEW5EYXEZKASQVC8XDGARN",
    amount: "500000000",
    memo: "0x46617563657400000000000000000000000000000000000000000000000000000000",
  },
}
```

---

So with all that in mind, the BNS name should be provided to the script for lookup, same with the address, so that the script can return the result of any address.

The agent can know it's own address by first running the wallet tool to get the info, then passing that to the BNS tool, likely as two separate tasks handled by the crew.

Hopefully that helps clear things up, feel free to comment back with any questions!

**Comment by Rapha-btc** [comment]
I am missing the basics here, thus this pull request was 80% ai generated.

I would love to have a video that onboards me to the code step by step. I'm talking very basic stuff here.

So although I can see that you made a significant effort reviewing my pull, and hopefully I didn't waste your time here... the truth here is that I don't have enough information to be able to bridge myself to the final job here. However, I will try. I'm not someone who gives up, but it might take more time than during this bounty competition. Bear with me, and count me in. Ai and BTC working group to the moon Baby. @whoabuddy

**Comment by Rapha-btc** [comment]
there's a time for learning and a time for doing, 

for now only, I leave the bounty to someone who is already operational here so that I can focus on stuff I can ship and that is needed yesterday...

while I'm seeking a way to onboard myself to the group - any material on the basic stuff is welcomed Jason @whoabuddy

**Comment by whoabuddy** [comment]
I think the best place to start is looking at the README for `agent-tools-ts` and see if you can run an existing script.

There are some examples of how to do that in my [previous comment](https://github.com/aibtcdev/agent-tools-ts/pull/7#issuecomment-2168527785) as well as what the results look like.

A tool is something the AI can decide to use in order to answer a question.  A simple example is that agents are bad at math so they often have a `calculator` tool defined and return the result.

If you ask an agent to compute 7+3 it will:

- recognize that this is math and it should use a tool
(usually through the initial prompting / agent definition)
- use the tool `calculator` and provide the input `7+3`
(it can get an error if it uses it wrong and try again)
- receive the result `10` and create a final answer

In the same way if we want an agent to perform an on-chain task, we need to create a tool for it, such as:

- [sign a message and extract public key](https://github.com/aibtcdev/agent-tools-ts/blob/main/src/wallet/sign-message-example.ts)
- [get wallet index, address, and nonce](https://github.com/aibtcdev/agent-tools-ts/blob/main/src/wallet/get-wallet-status.ts)
- [get provided transaction info](https://github.com/aibtcdev/agent-tools-ts/blob/main/src/wallet/get-transaction.ts)
- [get wallet balance for a token](https://github.com/aibtcdev/agent-tools-ts/blob/main/src/stacks-m2m-aibtc/get-balance.ts)
- [pay invoice by resource name](https://github.com/aibtcdev/agent-tools-ts/blob/main/src/stacks-m2m-v2/pay-invoice-by-resource-name.ts)
- etc... etc...

Each tool uses Stacks.js libraries to access wallet / blockchain.
Each tool is designed to do one thing and one thing only.
Each tool can have an optional single input.
Each tool should return information for the LLM.
Each tool should describe errors so they can be fixed on the next call.

This flow can be modified but represents the default way an agent will use a tool and how they are currently defined.

**Comment by whoabuddy** [comment]
@Rapha-btc thank you for the submission! The bounty has been claimed [per the issue comment](https://github.com/aibtcdev/agent-tools-ts/issues/4#issuecomment-2187396121), but keep an eye out for the next one!

**Pull request closed without merging**
